wneessen/go-mail

client.go, doc.go, msg.go, msg_test.go, msgwriter.go, msgwriter_test.go
As suggested in #3 we are renaming the `msg.Write()` method to `msg.WriteTo()` so that the `io.WriteTo` interface is satisfied. An alias method `msg.Write()` has been implemented for compatbility reasons.
=> Rename Write() to WriteTo() so it satisfies the io.WriteTo interface

msg.go
For the WriteToSendmail* methods the STDIN pipe should be closed so that a forced EOF is sent to the sending program
=> Address #5

msg.go
I discovered a couple more issues and I hope this PR will fix them.
1. Interaction with `sendmail` still "hangs", because Stderr is read before Stdin was closed, should be reversed.
2. Stderr was not read, because `io.Reader`'s `Read` method does not read into nil slice, according to documentation it will read up to `len(p)` where `p` is byte slice.
3. After explicit call to close of Stdin pipe was added, there is no need in deferred `Close`, plus according to documentation both Stderr and Stdin pipes will be closed automatically when `Wait` sees program exit.
=> Fix sendmail invocation

README.md, msg.go, msg_test.go
This PR adds a `Msg.Read()` method which satisfies the `io.Reader` interface
Closes #11
=> Msg.Read() to satisfy io.Reader

README.md, doc.go, msg.go, msg_test.go
This PR implements full support for html/template and text/template. It will allow to set the message body, alternative body as well as attachments/embeds using the Go template engine.
=> Template attachments

go.mod, msg.go, msg_test.go, msg_totmpfile.go, msg_totmpfile_116.go
This PR adds support for storing the output of a `Msg` into a file. Either an automatically generated temp file using `Msg.WriteToTempFile` or by providing ones own file name using `Msg.WriteToFile`.
Closes #18
=> Add support for storing mail messages in files

msg.go, msg_test.go
- Added `EmbedFromEmbedFS()` to allow embedding from embed.FS
- Added `AttachFromEmbedFS()` to allow attaching from embed.FS
- Added `fileFromEmbedFS()` as internal method for both other m
methods to attach/embed the embed.FS file
=> Closes #29: Allow attaching/embedding from embed.FS

base64_writer.go, msgwriter.go
Hopefully addresses #37 too.
By default, the encoding/base64 in Go does not add line breaks to its output. This patch introduces the Base64LineBreaker which satisfies the io.WriteCloser interface. Attachments are now correctly broken up into maximum of 76 chars. This hopefully satisfies the requirements of more strict mail servers, that do not allow lines longer than 78 chars (SHOULD)/998 chars(MUST) - see: https://www.rfc-editor.org/rfc/rfc5322#section-2.1.1
=> Fixes bug with attachment encoding

msg.go, msg_test.go
For Middlware to act on generic headers, we need to provide a way to access them. `Msg.GetGenHeader()` returns the value of the requested header of the Msg.
=> Add GetGenHeader to Msg

msg.go, part.go, part_test.go
Closes #60
This PR introduces a couple of new methods on the `Msg` as well as the `Part`. This will help the `Msg.Middleware` to be more extensible since we allow access not only to headers but also to body parts.
To get the Msg body parts, one can now utilize the `Msg.GetParts()` methods to get the list of currently assigned message parts to the `Msg`.
Each `Part` has now an additional list of getters/setters, to read and modify the given part:
* `Part.GetContent()`: get the parts content
* `Part.GetContentType()`: get the parts content type
* `Part.GetEncoding()`: get the parts encoding
* `Part.GetWriteFunc()`: get the parts write function
Each of these `Part.Get*()` methods also has an corresponding `Part.Set*()` methods what overrides the current value
=> Expose Msg bodypart fields

msg.go, msg_test.go
This PR introduces a couple of new methods on the `Msg`. This will help the `Msg.Middleware` to deal with `Msg` attachments.
To get the `Msg` attachments, we can now use the `Msg.GetAttachments()` methods to get the list of currently assigned attachments to the Msg.
To set the `Msg` attachments, we can now use the `Msg.SetAttachments()` methods to set a list of `*File` as `Msg` attachments.
=> Expose Msg attachments fields

.github/workflows/codecov.yml, .github/workflows/sonarqube.yml
The different Go version usages in the codecov workflow were missing the actual go setup set, which caused all tests to always run with Go 1.17. This PR fixes this
=> Fix codecov Go version setup

msg.go, msg_test.go, reader.go, reader_test.go
Initially the Msg implemented a io.Reader interface by providing a Read() methods. Unfortunately the method chosen for this method was very naive. It works fine for smaller messages but could result in wrong data returned for larger messages or i. e. used in a bufio.Reader with non consecutive reads. Since we did not track the position and state of the reading operation, duplicate data might be returned to the caller eventually even leading into infinite loops.
This PR fixes the issue be introducing a new `Reader` type. The `Reader` type satisfies the `io.Reader` interface and returns the data properly as well as returns `EOF` in case the end of data is reached.
The initial `Read()` method has been removed from the `Msg` type which and instead a `NewReader()` method has been introduced …
=> New Reader type

msg.go, msg_test.go
For middlewares to be able to access the fully written mail message, we need a way to execute WriteTo without the calling middleware to be handled, otherwise we end up in an infinite loop
Therefore, this PR introduces the MiddlewareType and the corresponding change of the Middleware interface. We now require to return the MiddlewareType when the Type() method on the interface is called
This way we can also introduce the WriteToSkipMiddleware method which takes a MiddlewareType as argument. This will allow us to use a WriteTo call with the initiating Middleware to be skipped
=> Introducing MiddlewareType and WriteToSkipMiddleware

msg.go, msg_test.go, random.go, random_test.go
This PR closes #74. It makes sure that generated message IDs via SetMessageID() are truly random and unique
=> Fixed SetMessageID message ID generation

msg.go, msg_test.go, msgwriter.go
With the SetHeaderPreformatted() method we have the ability to set headers that are already preformatted by the user and will not be altered in the mail message output
This PR resolves #76
=> Add SetHeaderPreformatted() method

client.go, client_119.go, client_120.go, client_test.go
`Client.Send()` provides the possibility to send multiple `*Msg` in one go. If one of the `*Msg` caused an error with the sending mail server, we were returning completely, while not processing any `*Msg` that came after the failing message.
This PR fixes this behaviour by processing each message first and then return a accumulated error in case any of the `*Msg` processing failed
Additionally, this PR separates the `Client.Send()` method into two different versions. One that makes use of the new `errors.Join()` functionality that is introduced with Go 1.20 and one that handles it the old way for any supported version lower than Go 1.20
=> Fix #85: Client.Send() failing for all messages if one is broken

client.go
This ensures the configured tls.Config is used with the tls.Dialer.
=> fix: tls config unused with dialer

client.go, client_test.go
This allows disabling the Noop command during the dial. This is useful for servers which delay potentially unwanted clients when they perform commands other than AUTH.
=> feat: without noop option

client_119.go, client_120.go, client_test.go, doc.go, msg.go, senderror.go, senderror_test.go
This PR introduces the `SendError` type which implements the error interface as solution for #90.
A new `senderror` field has been added to the `Msg` as well, so introduce this type to it.
I've also added different error variables that indicate the different things that can go wrong during mail delivery. These variables can be checked for, for each `Msg` using the `errors.Is` and `errors.As` methods. Additionally, the `SendError` has a `isTemp` field that indicates if the delivery error is of temporary nature and can be accessed via the `SendError.IsTemp()` method.
The `Error()` method of `SendError` will return a detailed error string on why the `Msg` could not be delivered.
Additionally, `HasSendError()`, `SendErrorIsTemp()` and `SendError()` methods have been added to `Msg`. While …
=> Introduction of new error type for sending errors

auth/auth_test.go, auth/login.go, client_test.go
This fixes #94 and basically reverts d0f0435. As James points out correctly in #94, we should not assume specific responses from the server. As long as the spec is followed and the server returns the correct SMTP code, we should not do our own magic.
I've also extended the `getTestConnection` method in client_test.go, so that we can specify more test environment options like `TEST_PORT` and `TEST_TLS_SKIP_VERIFY`. This was needed for testing with the ProtonMail Bridge which listens on a different port and has non-trusted certificates.
=> Fix SMTP AUTH LOGIN method for servers with uncommon success messages

client.go, client_test.go, smtp/smtp.go, smtp/smtp_test.go
Resolves #101.
Since we now have full control over the SMTP client we can also access the message input and output.
This PR introduces a new debug logging feature. Via the `Client.WithDebugLog` the user can enable this feature. It will then make use of the new `smtp/Client.SetDebugLog` method. Once the flag is set to true, the SMTP client will start logging incoming and outgoing messages to os.Stderr.
Log directions will be logged accordingly. 
- `C --> S` means Client to Server communication
- `C <-- S` means Server to Client communication
Example:
=> Implement SMTP client debug logging

msg.go, msgwriter.go, part.go, part_test.go
This PR introduces a new struct field for the message parts: `del`. If the del flag is set to `true`, the msgWriter will ignore this part during the writing process. Additionally, the `part` has now a `Delete` method that lets the user mark the part as deleted
This allows middleware to take further control of the Msg and is part of #107.
=> Introducing Msg part deletion

msg.go, msg_test.go
These two methods work analogous to the `*Attachments()` methods and provide the user with access to the embedded files.
=> Introduce GetEmbeds() and SetEmbeds()

msg.go, msg_test.go
Fixes #110 
`Msg.AttachReader()` would not output the attached file after consecutive writes (e.g. a write to a file and then send via Client).
This PR fixes this behaviour by first reading the io.Reader into memory and then creating a new `bytes.Reader`, which does support seeking. In the writeFunc we then seek to position 0 after a successful `io.Copy`. This is probably not the most memory efficient way of handling this, but otherwise we'll have to break the `io.Reader` interface.
Additionally, a new way of attaching/embedding files has been added: `Msg.AttachReadSeeker()` and `Msg.EmbedReadSeeker()` which take a ´io.ReadSeeker` as argument instead. These two methods will skip the reading into memory and make use of the `Seek` method of the corresponding interface instead.
=> Fix Attach/EmbedReader and implement Attach/EmbedReadSeeker

client.go, client_test.go, log/log.go, log/stdlog.go, log/stdlog_test.go, smtp/smtp.go, smtp/smtp_test.go
As stated in https://github.com/wneessen/go-mail/pull/102#issuecomment-1411956040 it would be beneficial if, instead of forcing the Go stdlib logger on the user to provide a simple interface and use that for logging purposes.
This PR implements this simple log.Logger interface as well as a standard logger that satisfies this interface. If no custom logger is provided, the Stdlog will be used (which makes use of the Go stdlib again).
Accordingly, a `Client.WithLogger` and `Client.SetLogger` have been implemented. Same applies for the smtp counterparts.
Closes #112
=> Implement Logger interface

encoding.go, file.go, file_test.go, header.go, msg.go, msg_test.go, msgwriter.go, msgwriter_test.go, part.go, part_test.go
This PR adds functionalities for middlware (in particular the new OpenPGP middleware) to provide more access to the `Msg`. 
In detail:
* The `File` type now has additional fields: `ContentType`, `Desc` and `Enc` with corresponding `FileOption´ methods to stear those
* A new `PGPType` has been added which can be set as part of the `Msg` struct using the `WithPGPType` option method and a `SetPGPType` setter method
* 3 PGPTypes have been added: `NoPGP`, `PGPEncrypt` and `PGPSignature`
* If a PGPType is set, the msgWriter will produce different MIME headers for the content types
* Msg parts received a `description` field which will be reflected in the `Content-Description` header of the part. Corresponding Option-, getter- and setter methods have been added: `WithPartContentDescription`, …
=> Provide more ways for middleware to interact with mail parts

msg.go
Encoding makes no sense at this point and leads to parsing errors. Encoding is applied in SetGenHeader
=> fix: parsing of ReplyTo with special characters

smtp/smtp.go
Since we are Go <1.20 compatible, we can't easily combine errors here. The suggested golangci-lint fix will not work neither, since the %w verb can't be used twice. Therefore, for now we will ignore the linting error
Closes #119
=> Make golangci-lint happy again

smtp/smtp_test.go
Fixes #121. `defer` in for loops can possibly lead to leaks.
The whole handling including the defer are now moved into anonymous functions outside the for loop and are called form the loop instead. This way the defer is handle when the inline function finishes
=> Remove defer from for loops

.cirrus.yml, auth.go, client.go, client_test.go, smtp/auth_xoauth2.go, smtp/smtp.go, smtp/smtp_test.go
fixes #129
The Microsoft variant is untested. Do no merge.
If in the meantime you have suggestions to improve the code, they are welcome.
If anyone can share a Microsoft Exchange Online account for testing and is interested in this feature, please contact me privately
=> add Oauth2 support

log/jsonlog.go, log/jsonlog_test.go, log/log.go
This PR introduces a new type 'JSONlog' that satisfies the Logger interface for structured JSON logging. This includes new methods 'Debugf', 'Infof', 'Warnf' and 'Errorf' to log messages at different levels and an associated test 'jsonlog_test.go' to ensure correct functionality. This enhances the logging functionality by providing clarity in logs and eases debugging process.
=> #142 Add structured JSON logger and associated tests

msg.go, msg_test.go
See issue #147.
I added three methods in the Msg file.
- Msg.UnsetAllAttachments()
- Msg.UnsetAllEmbeds()
- Msg.UnsetAllParts()
If there is any error, please tell me, and I will fix it.
=> #147 add remove attachments and embeds methods

msg.go, msg_test.go
Added new methods `ToFromString()`, `CcFromString()` and `BccFromString()` in msg.go file to handle strings of comma-separated email addresses.
Closes #152
=> Add new methods and tests for handling email addresses

client.go, msg.go, msg_test.go, msgwriter.go, reader.go, reader_test.go, senderror.go
I've taken some time to go through the code, searching for potential null pointer exceptions. A couple of instances were found. This PR is a collection of all the fixes. This should improve the code quality. No functionality was changed, only more guarding against null pointer exceptions were added.
=> Eleminate potential null pointer exceptions

msg.go, msg_test.go
Not returning an error here causes a panic when sending (`Header` in `File` object is a null map).
=> Added return error to `fileFromReader`

smtp/auth_login.go, smtp/smtp_test.go
This adds support for the auth login extension draft. This effectively is a draft that expired and was deprecated in favor of the `AUTH PLAIN` SASL extension. Microsoft is the only entity that I can find that has published a `AUTH LOGIN` SASL extension specification (which is currently supported), and Google seems to have adopted it too. 
This makes the Microsoft specification easily the most popular however there are some SMTP servers still using the version that was never formally published (including [Stalwart Mail Server](https://stalw.art/) [<sup>GitHub</sup>](https://github.com/stalwartlabs/mail-server) currently - I am trying to convince the developer to use the modern standard and have an opt in fallback to the deprecated/legacy/non-standard variant).
I've added documentation and …
=> feat(smtp): auth login extension draft support

smtp/auth_cram_md5.go, smtp/auth_cram_md5_118.go, smtp/auth_login.go, smtp/auth_plain.go, smtp/auth_xoauth2.go, smtp/smtp.go
This is a sync with the net/smtp upstream as committed here: https://github.com/golang/go/commit/1d45a7ef560a76318ed59dfdb178cecd58caf948#diff-4f6f6bdb9891d4dd271f9f31430420a2e44018fe4ee539576faf458bebb3cee4.
=> Upstream sync / refine function comments to include return type GoDoc links

client_119.go, client_120.go, client_test.go, msg.go
This update introduces a new property, `isDelivered`, in the message struct to track if a message has been successfully sent or not. Additionally, this also includes a new helper function `IsDelivered` to easily retrieve the status. This feature enhances the tracking capabilities of outgoing messages across different client files.
This PR will address #166
=> Add delivery status indication for messages

.cirrus.yml
The FreeBSD version used for testing in .cirrus.yml has been updated from 12.4 to 14.0. This change ensures that the tests run on the latest stable version of the operating system, providing more reliable and up-to-date test results.
=> Update FreeBSD version in .cirrus.yml

msg.go, msgwriter.go, msgwriter_test.go, part.go, part_test.go
Charset support has been added in the 'Part' struct. A 'SetCharset' method and a 'WithPartCharset' option have been added to override the default Part charset. The 'writePart' function in msgWriter now accommodates the charset defined at the Part level, defaulting to the previous functionality if not set.
This closes #171
=> Add Charset support for message parts

.golangci.toml, header.go, msg.go, msg_test.go, smtp/smtp_test.go
A new "X-Auto-Response-Suppress" header has been added. The SetBulk method has been updated to include this new header, as it is recommended for automated emails. This functionality is tested in the msg_test.go file.
=> Add "X-Auto-Response-Suppress" header and update SetBulk method

.github/workflows/codecov.yml, .github/workflows/golangci-lint.yml, .github/workflows/sonarqube.yml
The Go version has been updated to '1.22' in the 'sonarqube.yml', 'golangci-lint.yml', and 'codecov.yml' GitHub action workflow files. This includes an additional modification for the Go versions matrix and condition statements in the 'codecov.yml' workflow.
=> Update Go version in GitHub workflow files

auth.go, client_test.go
Introduced the SMTPAuthNoAuth mechanism in the auth.go file meant for instances where authentication is not required or supported. Adjusted tests in client_test.go to account for this new mechanism. Minor order modifications were also made to the list of supported SMTP AUTH types and respective tests for better consistency.
Closes #176
=> Update SMTP authentication mechanisms and related tests

b64linebreaker.go, client.go, client_119.go, client_120.go, client_test.go, file.go, log/jsonlog.go, log/jsonlog_test.go, log/stdlog.go, log/stdlog_test.go, msg.go, msg_test.go, msgwriter.go, msgwriter_test.go, part.go, part_test.go, random.go, reader.go, reader_test.go, senderror.go, tls.go
This PR updates the whole code base with better, more readable variables names to address #179. The code in the `smtp/` directory has been left untouched so that syncing with the upstream stdlib is not made more complicated than it has to be.
Closes #179.
=> Refactor variable names for readability

.github/dependabot.yml, .github/workflows/dependency-review.yml, .github/workflows/scorecards.yml
This commit adds SPDX license headers to GitHub workflow files: scorecards.yml, dependency-review.yml, and dependabot.yml. This ensures that the license and copyright information is easily available for everyone to see.
=> Add SPDX license headers to GitHub workflow files

.github/workflows/reuse.yml, .github/workflows/sonarqube.yml
This commit adds read permissions for 'contents' in the GitHub workflow files sonarqube.yml and reuse.yml. This allows these specific workflows to access the relevant contents they need for execution.
=> Add read permissions to GitHub workflow files

client.go
The update modifies the client's handling of port selection when configuring SSL/TLS connections. The clients' functions `WithSSLPort`, `WithTLSPortPolicy`, `SetTLSPortPolicy`, and `SetSSLPort` are revised to avoid overriding previously set ports. Additionally, the deprecation notes have been removed and replaced with notes on best-practice recommendations, referring the new *Port*() methods. This change revises #105 and takes the comments made in #181 into account.
This PR closes #181
=> Refine SMTP port selection and fallback logic

smtp/smtp_test.go
The format string for the Debugf method calls within the smtp_test.go file have been updated. Previously, the format string was empty, but it has now been changed to "%s" to align with the standard formatting expectations, improving the correctness of the tests.
=> Update format string in Debugf method calls in tests

README.md, doc.go, eml.go, eml_test.go, encoding.go, encoding_test.go, file.go, file_test.go, header.go, header_test.go, msg.go, msg_test.go, msgwriter.go
This PR introduces an EML parser to go-mail. It allows to read generic EML data from a file, a string or a reader into a go-mail `Msg` struct. It supports all types of message parts and encodings. It should be able to recognize Mulitpart messages as well as attachments and embeds (inline attachments).
This PR closes #145
=> Add EML parser

msg.go, msg_test.go
The GetBoundary method has been added to the Msg struct in msg.go. Alongside this, a corresponding test method, TestMsg_GetBoundary, was introduced in msg_test.go to ensure the proper working of GetBoundary. This new method returns the boundary string of the Msg, which was previously inaccessible.
=> Add GetBoundary method and corresponding test

eml.go, eml_test.go, encoding.go, encoding_test.go
This PR enhances the EML parsing to handle 7bit (and partly 8bit) content transfer encodings - especially in multi-part messages. Updated related test cases to verify the correct handling of these encodings. This ensures compliance with RFC2045.
This PR closes #262
=> Add 7bit support for EML parsing

eml.go, eml_test.go
Added a new example email and modified tests to include an RFC 5322 format. Refactored the code to handle cases where the Content-Type header is missing by defaulting to plain text (7bit, US-ASCII). Deleted redundant test cases that no longer apply.
This PR closes #271
=> Refactor: Handle missing Content-Type as plain text

msg.go, msg_test.go
The method `SetAttachements` is probably a typo: In all other methods it's correctly written "Attachments", so this method should be aligned.
=> Fix typo / inconsistency in Msg method

smtp/auth_login.go
Some email services, such as smtp.163.com and smtpdm.aliyun.com, return "334 dXNlcm5hbWU6" for "username:". For compatibility, support for "username:" and "password:" has been added.
=> Support lowercase username and password challenge

.golangci.toml, b64linebreaker.go, msg.go, msgwriter_test.go
=> Fix linter errors

client.go, client_119.go, client_120.go, client_test.go, msg.go, msg_test.go, senderror.go, senderror_test.go
The error handling was refactored in accordance to #168. Errors are not nested into each other anymore. The send logic for a single message has been moved to the non-version-specific Client.go while the version-specific only handle multi-message handling and error combination. Error messages now also refer to a message ID of the message that failed (if present), for easier debugging.
This PR closes #168
=> Improved error handling

.github/workflows/codecov.yml, client_119.go, client_test.go, senderror.go, senderror_test.go
This PR introduces a simple test SMTP server that can be used to more granuarly test different error scenarios, that are hard to simulate with a real mail server. More tests for the `Client` have been added as well, these should also test some `SendError` functionality.
Additionally two new `SendError` methods have been added (as suggested by @mitar in https://github.com/wneessen/go-mail/pull/301#issuecomment-2363265243) : 
- `MessageID()`: returns the message ID of the affected `Msg`
- `Msg()`: returns a pointer to the affectes `Msg`
=> Improved client error testing

client_test.go
Changed the test email address from go-mail@mytrashmailer.com to couttifaddebro-1473@yopmail.com. This new address is expected to be used for sending test mails.
=> Update test recipient email in client tests

smtp/auth.go, smtp/auth_login.go, smtp/auth_plain.go, smtp/auth_scram.go, smtp/smtp_test.go
This PR adds more tests to the `smtp` package, especially the auth parts.
=> More test coverage for smtp/auth

.cirrus.yml, .github/workflows/codecov.yml, .github/workflows/offline-tests.yml, .github/workflows/sonarqube.yml
We are currently running tests for all OS and 3 Go versions with actual connections to real mail servers. These cause a lot of traffic and are therefore much likely to fail due to connection timeouts. The actual online tests are much to redundant right now.
This PR updates the workflow to only run "online" tests on the latest Go version for each of Linux, Windows and MacOS. The Sonarqube test has been converted to "offline" tests as well. Additionally we now run "offline" tests for the latest 4 Go releases on all OSes instead.
=> Update GH test workflows

.github/workflows/codecov.yml, .github/workflows/offline-tests.yml, .github/workflows/sonarqube.yml
This PR refines the paths in GitHub Actions workflows to more precisely track changes in Go-related files and specific workflow files. General `.github/**` paths have been replaced with explicit references to relevant workflow files within `.github/workflows`.
=> Update GitHub Actions paths for Go and workflow files

smtp/smtp_test.go
Extended SMTP tests to include SCRAM-SHA-1-PLUS and SCRAM-SHA-256-PLUS authentication mechanisms. Adjusted the `startSMTPServer` function to accept a hashing function and modified the server logic to handle TLS channel binding.
=> Add support for SCRAM-SHA-1-PLUS and SCRAM-SHA-256-PLUS

client.go, client_test.go, smtp/smtp.go, smtp/smtp_test.go
This PR updates the `smtp.Client` to redact any kind of SMTP authentication data when debug logging is enabled. This will be the new default, since we want to offer sane defaults. If the user needs to see the authentication data anyways, two new Client options have been added to enable the logging of auth data: `WithLogAuthData()` and `Client.SetLogAuthData(bool)`.
=> Redact logging of SMTP authentication data

auth.go, client.go, client_test.go
This PR fixes a regression introduced in v0.5.0. `SMTPAuthNoAuth` is now changed from an empty string to "NOAUTH". This value is set as default for the Client in `NewClient`. This way we always have a fixed assignment and an empty string would not skip authentication. The `auth()` method has been updated to either assign the `smtp.Auth` function if `SMTPAuthType` is not set to "NOAUTH" or skip the part there is already an auth function set (this would only happen when `SetSMTPAuthCustom` or `"WithSMTPAuthCustom` were used.
If `SMTPAuthType` is set to an empty string, the authentication assignment would fail as it is a not supported mechanism, therefore making sure that the client wouldn't accidentaly skip the authentication at all.
A test has been added to test different auth switching …
=> Add default SMTP authentication type to NewClient

auth.go, eml.go, smtp/auth_login.go, smtp/smtp_test.go
=> Fix spelling errors

auth.go, auth_test.go
Implement the fig.StringUnmarshaler interface for SMTPAuthType to map strings to corresponding authentication types. Added comprehensive unit tests to ensure correct functionality for all supported auth type strings.
This allows users of fig to reference the `mail.SMTPAuthType` directly in their fig config.
=> Add fig.StringUnmarshaler support for SMTPAuthType

.github/workflows/ci.yml
This update ensures that the Dependency Review action has the correct references for base and head in pull request events. It helps in accurately reviewing dependency changes between the branches. Reference: https://github.com/actions/dependency-review-action/issues/456#issuecomment-1537840047
=> Add base-ref and head-ref to Dependency Review action

.github/workflows/ci.yml, random_test.go, senderror.go, senderror_test.go
This PR improves the tests for `random.go` and `senderror.go` for better test coverage.
=> More test improvements

client.go
Please, accept this review for fixing a panic on the `.Close()` method.
=> Fix(close): Access to nil variable causes panic

client_test.go
Introduce a unit test to ensure that invoking Close on a nil smtpclient instance returns nil without errors. This test accompanies the fix provided with PR #353
=> Add test for closing a nil smtpclient

.golangci.toml
Added gosec to the list of enabled linters in `.golangci.toml`. Defined specific exclusion rules to ignore certain false positives and context-specific issues flagged by gosec, ensuring the linter does not impose on intentional code practices.
=> Enable gosec linter and add exclusion rules

auth.go, client.go, client_test.go
This PR implements a mechanism to automatically discover and select the strongest supported SMTP authentication type. This feature simplifies the authentication process for users and enhances security by prioritizing stronger mechanisms based on server capabilities. Corresponding tests and documentation have been updated.
=> Add SMTP authentication auto-discovery

auth.go, auth_test.go
Extended the `UnmarshalString` function in `auth.go` to recognize "auto", "autodiscover", and "autodiscovery" as `SMTPAuthAutoDiscover`. Corresponding test cases were also added to `auth_test.go` to ensure proper functionality.
=> Add support for SMTP auto-discovery authentication

README.md, msg.go, msg_test.go
This PR adds support for generic file systems  that satisfy the `fs.FS` interface. Since `embed.FS` is such a file system, the `embed.FS` has been refactored to make use of the more generic `fs.FS` code. It also introduces two new methods `Msg.AttachFromIOFS` and `Msg.EmbedFromIOFS`. Documentation and tests have been updated accordingly.
=> Support attachments/embeds via io/fs.FS

.golangci.toml, client_test.go, quicksend.go, quicksend_test.go
This PR introduces the `QuickSend` function for sending emails quickly with TLS and optional SMTP authentication. Added comprehensive unit tests to ensure QuickSend works correctly with different authentication mechanisms and handles various error scenarios.
This feature is similar to the `SendMail` method of the `net/smtp` package, but make use of all go-mail `Client` and `Msg` features, including error checking and validations.
This method will create a new client that connects to the server at addr, switches to TLS if possible, authenticates with the optional AuthData provided in auth and create a new simple Msg with the provided subject string and message bytes as body. The message will be sent using from as sender address and will be delivered to every address in rcpts. QuickSend …
=> Add QuickSend feature

client.go, client_test.go
Introduced a sendMutex to synchronize access to shared resources in the DialAndSendWithContext method. This ensures thread safety when sending multiple messages concurrently. Added a corresponding test to verify the concurrent sending functionality.
This closes #380
=> Add mutex for concurrent send protection

quicksend.go
The opts parameter documentation was removed as it is no longer used in the quicksend function. This change helps in maintaining accurate and up-to-date code documentation and reduces potential confusion.
=> Remove unused opts parameter docstring

msgwriter.go, msgwriter_test.go
This PR introduces proper filename sanitization for attachments and embedded files. It will repace invalid characters with underscore `_` characters before encoding them. This prevents control (like new lines) and special characters like backslash or quotes from causing issues in MIME headers and file systems.
As a side effect this prevents newline characters from introducing a potential vulnerability by using filenames with newlines characters in it. 
We also make sure that the `Content-Description` header is properly encoded.
=> Improve filename sanitization in MIME headers

client.go, client_test.go
This PR adds support for connecting to a Unix Domain Socket instead of a TCP port.
The `Client` can be intructed to connect to a unix socket by prefixing the host with `unix://` (Example: ` mail.NewClient("unix:///var/spool/postfix/private/smtpunix")`
This feature is requested by the Forgejo project as part of a possible migration to go-mail: https://codeberg.org/forgejo/forgejo/issues/6028#issuecomment-2560355
=> Unix domain socket support

msgwriter.go
This PR fixes a regression that was introduced in the S/MIME signing code of v0.6.0 which caused the msgwriter to not add a newline between the first boundary and the multipart causing the mail to be unable to render in mail clients.
Fixes #412
=> Fix regression in multipart boundary writing

doc.go, msg_test.go, senderror_test.go, smtp/smtp_test.go
This PR prepares the v0.6.1 release. It bumps the version number and fixes some typos.
=> chore: prepare 061 release

.github/workflows/ci.yml, msg_test.go, quicksend_test.go
This PR adds more tests for the message processing that writes mails into memory and compares expected values. 
This closes #420
=> chore: improve tests for multipart messages

client_test.go
Introduce unit tests to verify the behavior of `DialAndSendWithContext` and `Send` methods when provided with `nil` messages. These tests ensure proper error handling and validation under such scenarios, improving robustness. This accompanies commit 4641da4 which was missing the tests.
=> Add tests for handling nil messages in email client

.golangci.toml, client.go, client_test.go, msg_test.go
This change re-introduces custom smtp.Auth support, which has been removed by accident. See #428. To make sure this does not happen again, a couple of tests have been added that make sure the custom auth is working as intended. This includes a `testCustomAuth` struct to verify the "CUSTOM" method and enhancements in the client to handle custom auth types. Resolves issue #428.
=> Fix regression of custom smtp.Auth not working

helper_test.go, msg_test.go, msgwriter_test.go, random_test.go
Tests involving broken rand.Reader are skipped for Go 1.24 and above due to upstream changes that prevent failures. A `getGoVersion` helper function is added to determine the runtime version, ensuring test compatibility and reducing false negatives. This PR closes #432.
=> Skip tests for broken rand.Reader on Go 1.24+.

.github/workflows/ci.yml, .golangci.toml
=> chore: update CI to Go 1.24

doc.go
Corrected a spelling error in the package description ("programmatic") for improved clarity. Bumped the package version from 0.6.1 to 0.6.2 to reflect this change.
=> Update version to 0.6.2 and fix typo in documentation

header.go, header_test.go, msg.go, msg_test.go, msgwriter.go
Changed `Reply-To` header to an `AddrHeader` type. Since `Reply-To` is actually an address header which formats the mail address accordingly, and not a generic header, this could lead to potential double encoding if the address and name contain special characters. 
This PR is potentially a breaking change, since we are changing a public type, but as long as the user makes use of `msg.ReplyTo()` or `msg.ReplyToFormat()` this should not cause any problems.
This PR fixes #440.
=> BREAKING CHANGE: Refactor Reply-To header handling.

b64linebreaker_test.go
* Fuzz Base64LineBreaker with various chunk sizes
* Check the count of written bytes reported by the base64 encoder
=> More Base64LineBreaker fuzzing

b64linebreaker.go, b64linebreaker_test.go, msgwriter.go
Rename `Base64LineBreaker` to `base64LineBreaker` and update associated methods, variables, and error messages. As Olivier Mengué pointed out in #444, making the API public was a poor choice by myself, since the struct has no public fields and since the `io.Writer` is required, nobody except go-mail would ever be able to use the API. This is a breaking change, but since nobody would be able to use the API anyways, it should not affect any user. This PR closes #444.
=> Make Base64LineBreaker private

eml.go, eml_test.go
Improve handling of multipart headers by addressing edge cases where multiple parameters are present. Add a new test case to validate parsing of EML files with attachments and metadata, fixing GH issue #457.
=> Fix multipart header parsing and add test for attachments with metadata

b64linebreaker.go
The count of bytes written is incorrectly reported by [`Base64LineBreaker.Write`](https://pkg.go.dev/github.com/wneessen/go-mail#Base64LineBreaker.Write). This issue is not visible externally as `Base64LineBreaker.Write` is only called via `encoding/base64.Encoder.Write` (like in the original implementation in stdlib `encoding/pem.lineBreaker`) which ignores the returned bytes count.
The issue is not visible either with the test suite (not even via the current fuzzing tests) because the tests also use `Base64LineBreaker` through the [`encoding/base64.Encoder`](https://pkg.go.dev/encoding/base64#Encoder).
So we could just keep the existing code. The only risk is if `encoding/base64` behavior changes in the future.
See also [CL 653675](https://go.dev/cl/653675) which aims to fix the same …
=> Fix "short writes" in Base64LineBreaker.Write

msg_test.go, smime_test.go
=> Improve PKCS7 test suite

.github/workflows/ci.yml, go.mod
- Bumped Go version from 1.24 to 1.25 across all workflows.
- Adjusted FreeBSD versions in test matrix to include 13.5 and 14.3 while removing 14.1.
=> Update CI configuration to support Go 1.25 and disable older versions

.github/workflows/ci.yml
- Added `macos-latest` to the test matrix in CI workflow.
- Resolved TODO by re-enabling macOS builds for testing.
=> Enable macOS builds in CI test matrix

doc.go, msg.go
- Replaced repetitive address string manipulation with `mailAddressStringWithoutName` helper function.
- Updated sender and recipient parsing logic to ensure proper handling of addresses without names.
- Improved clarity and maintainability by standardizing address formatting logic.
This fixes a regression introduced in v0.7.1 (see #497)
=> Refactored address handling for improved consistency and formatting
